language: generic
# dart:
#   - stable
os:
  - osx
sudo: false
# addons:
#     apt:
#         sources:
#           - ubuntu-toolchain-r-test # you need this source to get the right version of libstdc++6
#         packages:
#           - libstdc++6
#           - fonts-droid
before_script:
- cd ..
- git clone https://github.com/flutter/flutter.git --depth 1
- export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
# - flutter upgrade
- flutter doctor

script:
- cd $TRAVIS_BUILD_DIR
- flutter pub get
- flutter test --coverage

